// Code generated by Fern. DO NOT EDIT.

package sleep

import (
	context "context"
	v505 "github.com/tryVital/vital-go/v2"
	core "github.com/tryVital/vital-go/v2/core"
	internal "github.com/tryVital/vital-go/v2/internal"
	option "github.com/tryVital/vital-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get sleep summary for user_id
func (c *Client) Get(
	ctx context.Context,
	userId string,
	request *v505.SleepGetRequest,
	opts ...option.RequestOption,
) (*v505.ClientSleepResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get raw sleep summary for user_id
func (c *Client) GetRaw(
	ctx context.Context,
	userId string,
	request *v505.SleepGetRawRequest,
	opts ...option.RequestOption,
) (*v505.RawSleep, error) {
	response, err := c.WithRawResponse.GetRaw(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get Sleep stream for a user_id
func (c *Client) GetStreamBySleepId(
	ctx context.Context,
	// The Vital Sleep ID
	sleepId string,
	opts ...option.RequestOption,
) (*v505.ClientFacingSleepStream, error) {
	response, err := c.WithRawResponse.GetStreamBySleepId(
		ctx,
		sleepId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
