// This file was auto-generated by Fern from our API Definition.

package api

type InsuranceSearchDiagnosisRequest struct {
	DiagnosisQuery string `json:"-" url:"diagnosis_query"`
}

type PayorSearchRequest struct {
	InsuranceName string `json:"insurance_name" url:"-"`
}
