// This file was auto-generated by Fern from our API Definition.

package api

type MenstrualCycleGetRequest struct {
	// Provider oura/strava etc
	Provider  *string `json:"-" url:"provider,omitempty"`
	StartDate string  `json:"-" url:"start_date"`
	EndDate   *string `json:"-" url:"end_date,omitempty"`
}
