// This file was auto-generated by Fern from our API Definition.

package api

type MenstrualCycleGetRequest struct {
	// Provider oura/strava etc
	Provider  *string `json:"-"`
	StartDate string  `json:"-"`
	EndDate   *string `json:"-"`
}
