// This file was auto-generated by Fern from our API Definition.

package api

import (
	core "github.com/fern-vital/vital-go/core"
)

type CreateApiKeyBody struct {
	Label string `json:"label"`
}

type PriorityCreate struct {
	Id                   *core.Optional[int]    `json:"id,omitempty"`
	Priority             int                    `json:"priority"`
	PriorityCreateTeamId string                 `json:"team_id"`
	SourceId             int                    `json:"source_id"`
	DataType             *core.Optional[string] `json:"data_type,omitempty"`
}

type TeamCreate struct {
	SvixAppId                           *core.Optional[string]            `json:"svix_app_id,omitempty"`
	ClientId                            *core.Optional[string]            `json:"client_id,omitempty"`
	ClientSecret                        *core.Optional[string]            `json:"client_secret,omitempty"`
	ApiKey                              *core.Optional[string]            `json:"api_key,omitempty"`
	AirtableApiKey                      *core.Optional[string]            `json:"airtable_api_key,omitempty"`
	AirtableBaseId                      *core.Optional[string]            `json:"airtable_base_id,omitempty"`
	WebhookSecret                       *core.Optional[string]            `json:"webhook_secret,omitempty"`
	FfWheelEnabled                      *core.Optional[bool]              `json:"ff_wheel_enabled,omitempty"`
	FfAppleMobileAppEnabled             *core.Optional[bool]              `json:"ff_apple_mobile_app_enabled,omitempty"`
	LabTestsPatientCommunicationEnabled *core.Optional[bool]              `json:"lab_tests_patient_communication_enabled,omitempty"`
	LabTestDelegatedFlowEnabled         *core.Optional[bool]              `json:"lab_test_delegated_flow_enabled,omitempty"`
	PhysicianNetwork                    *core.Optional[PhysicianNetworkT] `json:"physician_network,omitempty"`
	Id                                  *core.Optional[string]            `json:"id,omitempty"`
	Name                                string                            `json:"name"`
	SubscriptionStatus                  *core.Optional[string]            `json:"subscription_status,omitempty"`
}

type GetSourcePrioritiesV2TeamSourcePrioritiesGetRequest struct {
	DataType *string `json:"-"`
}

type SearchTeamUsersByUuidOrClientUserIdV2TeamUsersSearchGetRequest struct {
	QueryId *string `json:"-"`
}

type UpdateApiKeyBody struct {
	Label string `json:"label"`
}

type UpdateSourcePrioritiesV2TeamSourcePrioritiesPatchRequest struct {
	TeamId string `json:"-"`
}

type TeamUpdate struct {
	LabTestsPatientCommunicationEnabled *core.Optional[bool]   `json:"lab_tests_patient_communication_enabled,omitempty"`
	SubscriptionStatus                  *core.Optional[string] `json:"subscription_status,omitempty"`
	LogoUrl                             *core.Optional[string] `json:"logo_url,omitempty"`
}
