// This file was auto-generated by Fern from our API Definition.

package api

type PostUserBloodPressureV2TimeseriesUserIdBloodPressurePostRequest struct {
	VitalIosSdkVersion     *string `json:"-"`
	VitalAndroidSdkVersion *string `json:"-"`
}
