// This file was auto-generated by Fern from our API Definition.

package api

type VitalsTimeseriesRequestRequest struct {
	VitalIosSdkVersion     *string `json:"-"`
	VitalAndroidSdkVersion *string `json:"-"`
}

type VitalsBloodOxygenRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsBloodPressureRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCaffeineRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCaloriesActiveRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCaloriesBasalRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCholesterolRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCholesterolHdlRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCholesterolLdlRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsCholesterolTotalRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsDistanceRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsFloorsClimbedRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsGlucoseRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsHeartrateRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsHrvRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsHypnogramRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsIgeRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsIggRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsMindfulnessMinutesRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsRespiratoryRateRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsStepsRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsTriglyceridesRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}

type VitalsWaterRequest struct {
	Resource TimeseriesResource `json:"-"`
	// Provider oura/strava etc
	Provider *string `json:"-"`
	// Date from in YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 00:00:00
	StartDate string `json:"-"`
	// Date to YYYY-MM-DD or ISO formatted date time. If a date is provided without a time, the time will be set to 23:59:59
	EndDate *string `json:"-"`
}
