// Code generated by Fern. DO NOT EDIT.

package team

import (
	context "context"
	vitalgo "github.com/tryVital/vital-go"
	core "github.com/tryVital/vital-go/core"
	internal "github.com/tryVital/vital-go/internal"
	option "github.com/tryVital/vital-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Post teams.
func (c *Client) GetLinkConfig(
	ctx context.Context,
	request *vitalgo.GetLinkConfigTeamRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.GetLinkConfig(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get team.
func (c *Client) Get(
	ctx context.Context,
	request *vitalgo.GetTeamRequest,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingTeam, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Search team users by user_id
func (c *Client) GetUserById(
	ctx context.Context,
	request *vitalgo.GetUserByIdTeamRequest,
	opts ...option.RequestOption,
) ([]*vitalgo.ClientFacingUser, error) {
	response, err := c.WithRawResponse.GetUserById(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetSvixUrl(
	ctx context.Context,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.GetSvixUrl(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// GET source priorities.
func (c *Client) GetSourcePriorities(
	ctx context.Context,
	request *vitalgo.GetSourcePrioritiesTeamRequest,
	opts ...option.RequestOption,
) ([]map[string]any, error) {
	response, err := c.WithRawResponse.GetSourcePriorities(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Patch source priorities.
func (c *Client) UpdateSourcePriorities(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]map[string]any, error) {
	response, err := c.WithRawResponse.UpdateSourcePriorities(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetPhysicians(
	ctx context.Context,
	request *vitalgo.GetPhysiciansTeamRequest,
	opts ...option.RequestOption,
) ([]*vitalgo.ClientFacingPhysician, error) {
	response, err := c.WithRawResponse.GetPhysicians(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
