// Code generated by Fern. DO NOT EDIT.

package link_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	vitalgo "github.com/tryVital/vital-go"
	client "github.com/tryVital/vital-go/client"
	option "github.com/tryVital/vital-go/option"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestLinkListBulkOpsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.ListBulkOpsLinkRequest{}
	_, invocationErr := client.Link.ListBulkOps(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/link/bulk_op", nil, 1)
}

func TestLinkBulkImportWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.BulkImportConnectionsBody{
		Provider: vitalgo.OAuthProvidersOura,
		Connections: []*vitalgo.ConnectionRecipe{
			&vitalgo.ConnectionRecipe{
				UserId:       "user_id",
				AccessToken:  "access_token",
				RefreshToken: "refresh_token",
				ProviderId:   "provider_id",
				ExpiresAt:    1,
			},
		},
	}
	_, invocationErr := client.Link.BulkImport(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/bulk_import", nil, 1)
}

func TestLinkBulkTriggerHistoricalPullWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.BulkTriggerHistoricalPullBody{
		UserIds: []string{
			"user_ids",
		},
		Provider: vitalgo.OAuthProvidersOura,
	}
	_, invocationErr := client.Link.BulkTriggerHistoricalPull(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/bulk_trigger_historical_pull", nil, 1)
}

func TestLinkBulkExportWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.BulkExportConnectionsBody{
		Provider: vitalgo.OAuthProvidersOura,
	}
	_, invocationErr := client.Link.BulkExport(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/bulk_export", nil, 1)
}

func TestLinkBulkPauseWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.BulkPauseConnectionsBody{
		UserIds: []string{
			"user_ids",
		},
		Provider: vitalgo.OAuthProvidersOura,
	}
	_, invocationErr := client.Link.BulkPause(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/bulk_pause", nil, 1)
}

func TestLinkTokenWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.LinkTokenExchange{
		UserId: "user_id",
	}
	_, invocationErr := client.Link.Token(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/token", nil, 1)
}

func TestLinkIsTokenValidWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.LinkTokenValidationRequest{
		Token: "token",
	}
	_, invocationErr := client.Link.IsTokenValid(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/token/isValid", nil, 1)
}

func TestLinkCodeCreateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.CodeCreateLinkRequest{
		UserId: "user_id",
	}
	_, invocationErr := client.Link.CodeCreate(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/code/create", map[string]string{"user_id": "user_id"}, 1)
}

func TestLinkStartConnectWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.BeginLinkTokenRequest{
		LinkToken: "link_token",
		Provider:  vitalgo.ProvidersOura,
	}
	_, invocationErr := client.Link.StartConnect(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/start", nil, 1)
}

func TestLinkTokenStateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.TokenStateLinkRequest{}
	_, invocationErr := client.Link.TokenState(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/link/state", nil, 1)
}

func TestLinkEmailAuthWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.EmailAuthLink{
		Email:    "email",
		Provider: vitalgo.ProvidersOura,
		AuthType: vitalgo.AuthTypePassword,
	}
	_, invocationErr := client.Link.EmailAuth(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/auth/email", nil, 1)
}

func TestLinkPasswordAuthWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.PasswordAuthLink{
		Username: "username",
		Password: "password",
		Provider: vitalgo.ProvidersOura,
		AuthType: vitalgo.AuthTypePassword,
	}
	_, invocationErr := client.Link.PasswordAuth(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/auth", nil, 1)
}

func TestLinkGenerateOauthLinkWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.GenerateOauthLinkLinkRequest{}
	_, invocationErr := client.Link.GenerateOauthLink(
		context.TODO(),
		vitalgo.OAuthProvidersOura.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/link/provider/oauth/oura", nil, 1)
}

func TestLinkConnectPasswordProviderWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.IndividualProviderData{
		Username: "username",
		Password: "password",
	}
	_, invocationErr := client.Link.ConnectPasswordProvider(
		context.TODO(),
		vitalgo.PasswordProvidersWhoop.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/provider/password/whoop", nil, 1)
}

func TestLinkCompletePasswordProviderMfaWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.CompletePasswordProviderMfaBody{
		MfaCode: "mfa_code",
	}
	_, invocationErr := client.Link.CompletePasswordProviderMfa(
		context.TODO(),
		vitalgo.PasswordProvidersWhoop.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/provider/password/whoop/complete_mfa", nil, 1)
}

func TestLinkConnectEmailAuthProviderWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.EmailProviderAuthLink{
		Email: "email",
	}
	_, invocationErr := client.Link.ConnectEmailAuthProvider(
		context.TODO(),
		vitalgo.EmailProviders(
			"freestyle_libre",
		),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/provider/email/freestyle_libre", nil, 1)
}

func TestLinkGetAllProvidersWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.GetAllProvidersLinkRequest{}
	_, invocationErr := client.Link.GetAllProviders(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/link/providers", nil, 1)
}

func TestLinkConnectManualProviderWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.ManualConnectionData{
		UserId: "user_id",
	}
	_, invocationErr := client.Link.ConnectManualProvider(
		context.TODO(),
		vitalgo.ManualProvidersBeurerBle.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/provider/manual/beurer_ble", nil, 1)
}

func TestLinkConnectDemoProviderWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.DemoConnectionCreationPayload{
		UserId:   "user_id",
		Provider: vitalgo.DemoProvidersAppleHealthKit,
	}
	_, invocationErr := client.Link.ConnectDemoProvider(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/link/connect/demo", nil, 1)
}
