// Code generated by Fern. DO NOT EDIT.

package labaccount

import (
	context "context"
	v505 "github.com/tryVital/vital-go/v2"
	core "github.com/tryVital/vital-go/v2/core"
	internal "github.com/tryVital/vital-go/v2/internal"
	option "github.com/tryVital/vital-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) GetTeamLabAccounts(
	ctx context.Context,
	request *v505.LabAccountGetTeamLabAccountsRequest,
	opts ...option.RequestOption,
) (*v505.GetTeamLabAccountsResponse, error) {
	response, err := c.WithRawResponse.GetTeamLabAccounts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
