// Code generated by Fern. DO NOT EDIT.

package user_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	vitalgo "github.com/tryVital/vital-go"
	client "github.com/tryVital/vital-go/client"
	option "github.com/tryVital/vital-go/option"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestUserGetAllWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.GetAllUserRequest{}
	_, invocationErr := client.User.GetAll(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user", nil, 1)
}

func TestUserCreateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.UserCreateBody{
		ClientUserId: "client_user_id",
	}
	_, invocationErr := client.User.Create(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user", nil, 1)
}

func TestUserGetTeamMetricsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetTeamMetrics(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/metrics", nil, 1)
}

func TestUserGetConnectedProvidersWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetConnectedProviders(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/providers/user_id", nil, 1)
}

func TestUserGetLatestUserInfoWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetLatestUserInfo(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/user_id/info/latest", nil, 1)
}

func TestUserCreateInsuranceWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.CreateInsuranceRequest{
		PayorCode:    "payor_code",
		MemberId:     "member_id",
		Relationship: vitalgo.ResponsibleRelationshipSelf,
		Insured: &vitalgo.VitalCoreSchemasDbSchemasLabTestInsurancePersonDetails{
			FirstName: "first_name",
			LastName:  "last_name",
			Gender:    vitalgo.GenderFemale,
			Address: &vitalgo.Address{
				FirstLine: "first_line",
				Country:   "country",
				Zip:       "zip",
				City:      "city",
				State:     "state",
			},
			Dob: vitalgo.MustParseDateTime(
				"2023-01-15",
			),
			Email:       "email",
			PhoneNumber: "phone_number",
		},
	}
	_, invocationErr := client.User.CreateInsurance(
		context.TODO(),
		"user_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user/user_id/insurance", nil, 1)
}

func TestUserGetLatestInsuranceWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetLatestInsurance(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/user_id/insurance/latest", nil, 1)
}

func TestUserUpsertUserInfoWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.UserInfoCreateRequest{
		FirstName:   "first_name",
		LastName:    "last_name",
		Email:       "email",
		PhoneNumber: "phone_number",
		Gender:      "gender",
		Dob: vitalgo.MustParseDateTime(
			"2023-01-15",
		),
		Address: &vitalgo.Address{
			FirstLine: "first_line",
			Country:   "country",
			Zip:       "zip",
			City:      "city",
			State:     "state",
		},
	}
	_, invocationErr := client.User.UpsertUserInfo(
		context.TODO(),
		"user_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v2/user/user_id/info", nil, 1)
}

func TestUserGetByClientUserIdWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetByClientUserId(
		context.TODO(),
		"client_user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/resolve/client_user_id", nil, 1)
}

func TestUserDeregisterProviderWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.DeregisterProvider(
		context.TODO(),
		"user_id",
		vitalgo.ProvidersOura.Ptr(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/v2/user/user_id/oura", nil, 1)
}

func TestUserGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.Get(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/user_id", nil, 1)
}

func TestUserDeleteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.Delete(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/v2/user/user_id", nil, 1)
}

func TestUserPatchWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.UserPatchBody{}
	invocationErr := client.User.Patch(
		context.TODO(),
		"user_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v2/user/user_id", nil, 1)
}

func TestUserUndoDeleteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.UndoDeleteUserRequest{}
	_, invocationErr := client.User.UndoDelete(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user/undo_delete", nil, 1)
}

func TestUserRefreshWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.RefreshUserRequest{}
	_, invocationErr := client.User.Refresh(
		context.TODO(),
		"user_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user/refresh/user_id", nil, 1)
}

func TestUserGetDevicesWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetDevices(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/user_id/device", nil, 1)
}

func TestUserGetDeviceWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetDevice(
		context.TODO(),
		"user_id",
		"device_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/user/user_id/device/device_id", nil, 1)
}

func TestUserGetUserSignInTokenWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.User.GetUserSignInToken(
		context.TODO(),
		"user_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user/user_id/sign_in_token", nil, 1)
}

func TestUserCreatePortalUrlWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &vitalgo.CreateUserPortalUrlBody{
		Context: vitalgo.CreateUserPortalUrlBodyContextLaunch,
	}
	_, invocationErr := client.User.CreatePortalUrl(
		context.TODO(),
		"user_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/user/user_id/create_portal_url", nil, 1)
}
