// Code generated by Fern. DO NOT EDIT.

package aggregate

import (
	context "context"
	v505 "github.com/tryVital/vital-go/v2"
	core "github.com/tryVital/vital-go/v2/core"
	internal "github.com/tryVital/vital-go/v2/internal"
	option "github.com/tryVital/vital-go/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) QueryOne(
	ctx context.Context,
	userId string,
	request *v505.QueryBatch,
	opts ...option.RequestOption,
) (*v505.AggregationResponse, error) {
	response, err := c.WithRawResponse.QueryOne(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetResultTableForContinuousQuery(
	ctx context.Context,
	userId string,
	queryIdOrSlug string,
	opts ...option.RequestOption,
) (*v505.AggregationResult, error) {
	response, err := c.WithRawResponse.GetResultTableForContinuousQuery(
		ctx,
		userId,
		queryIdOrSlug,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTaskHistoryForContinuousQuery(
	ctx context.Context,
	userId string,
	queryIdOrSlug string,
	request *v505.AggregateGetTaskHistoryForContinuousQueryRequest,
	opts ...option.RequestOption,
) (*v505.ContinuousQueryTaskHistoryResponse, error) {
	response, err := c.WithRawResponse.GetTaskHistoryForContinuousQuery(
		ctx,
		userId,
		queryIdOrSlug,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
