// Code generated by Fern. DO NOT EDIT.

package user

import (
	context "context"
	vitalgo "github.com/tryVital/vital-go"
	core "github.com/tryVital/vital-go/core"
	internal "github.com/tryVital/vital-go/internal"
	option "github.com/tryVital/vital-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// GET All users for team.
func (c *Client) GetAll(
	ctx context.Context,
	request *vitalgo.UserGetAllRequest,
	opts ...option.RequestOption,
) (*vitalgo.PaginatedUsersResponse, error) {
	response, err := c.WithRawResponse.GetAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// POST Create a Vital user given a client_user_id and returns the user_id.
func (c *Client) Create(
	ctx context.Context,
	request *vitalgo.UserCreateBody,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingUserKey, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// GET metrics for team.
func (c *Client) GetTeamMetrics(
	ctx context.Context,
	opts ...option.RequestOption,
) (*vitalgo.MetricsResult, error) {
	response, err := c.WithRawResponse.GetTeamMetrics(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// GET Users connected providers
func (c *Client) GetConnectedProviders(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) (map[string][]*vitalgo.ClientFacingProviderWithStatus, error) {
	response, err := c.WithRawResponse.GetConnectedProviders(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetLatestUserInfo(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) (*vitalgo.UserInfo, error) {
	response, err := c.WithRawResponse.GetLatestUserInfo(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateInsurance(
	ctx context.Context,
	userId string,
	request *vitalgo.CreateInsuranceRequest,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingInsurance, error) {
	response, err := c.WithRawResponse.CreateInsurance(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetLatestInsurance(
	ctx context.Context,
	userId string,
	request *vitalgo.UserGetLatestInsuranceRequest,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingInsurance, error) {
	response, err := c.WithRawResponse.GetLatestInsurance(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpsertUserInfo(
	ctx context.Context,
	userId string,
	request *vitalgo.UserInfoCreateRequest,
	opts ...option.RequestOption,
) (*vitalgo.UserInfo, error) {
	response, err := c.WithRawResponse.UpsertUserInfo(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// GET user_id from client_user_id.
func (c *Client) GetByClientUserId(
	ctx context.Context,
	// A unique ID representing the end user. Typically this will be a user ID number from your application. Personally identifiable information, such as an email address or phone number, should not be used in the client_user_id.
	clientUserId string,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingUser, error) {
	response, err := c.WithRawResponse.GetByClientUserId(
		ctx,
		clientUserId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeregisterProvider(
	ctx context.Context,
	userId string,
	// Provider slug. e.g., `oura`, `fitbit`, `garmin`.
	provider *vitalgo.Providers,
	opts ...option.RequestOption,
) (*vitalgo.UserSuccessResponse, error) {
	response, err := c.WithRawResponse.DeregisterProvider(
		ctx,
		userId,
		provider,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingUser, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) (*vitalgo.UserSuccessResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Patch(
	ctx context.Context,
	userId string,
	request *vitalgo.UserPatchBody,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Patch(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) UndoDelete(
	ctx context.Context,
	request *vitalgo.UserUndoDeleteRequest,
	opts ...option.RequestOption,
) (*vitalgo.UserSuccessResponse, error) {
	response, err := c.WithRawResponse.UndoDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Trigger a manual refresh for a specific user
func (c *Client) Refresh(
	ctx context.Context,
	userId string,
	request *vitalgo.UserRefreshRequest,
	opts ...option.RequestOption,
) (*vitalgo.UserRefreshSuccessResponse, error) {
	response, err := c.WithRawResponse.Refresh(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetDevices(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) ([]*vitalgo.ClientFacingDevice, error) {
	response, err := c.WithRawResponse.GetDevices(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetDevice(
	ctx context.Context,
	userId string,
	deviceId string,
	opts ...option.RequestOption,
) (*vitalgo.ClientFacingDevice, error) {
	response, err := c.WithRawResponse.GetDevice(
		ctx,
		userId,
		deviceId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetUserSignInToken(
	ctx context.Context,
	userId string,
	opts ...option.RequestOption,
) (*vitalgo.UserSignInTokenResponse, error) {
	response, err := c.WithRawResponse.GetUserSignInToken(
		ctx,
		userId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreatePortalUrl(
	ctx context.Context,
	userId string,
	request *vitalgo.CreateUserPortalUrlBody,
	opts ...option.RequestOption,
) (*vitalgo.CreateUserPortalUrlResponse, error) {
	response, err := c.WithRawResponse.CreatePortalUrl(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
