// Code generated by Fern. DO NOT EDIT.

package activity

import (
	context "context"
	vital "github.com/tryVital/vital-go"
	core "github.com/tryVital/vital-go/core"
	internal "github.com/tryVital/vital-go/internal"
	option "github.com/tryVital/vital-go/option"
	http "net/http"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Get activity summary for user_id
func (c *Client) Get(
	ctx context.Context,
	userId string,
	request *vital.ActivityGetRequest,
	opts ...option.RequestOption,
) (*vital.ClientActivityResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get raw activity summary for user_id
func (c *Client) GetRaw(
	ctx context.Context,
	userId string,
	request *vital.ActivityGetRawRequest,
	opts ...option.RequestOption,
) (*vital.RawActivity, error) {
	response, err := c.WithRawResponse.GetRaw(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
